In [ ]:
print("hello world")

hello world


# Numpy
fast mathematical operations
working with arrays (better than python lists)


In [1]:
%pip install numpy

Defaulting to user installation because normal site-packages is not writeable
You should consider upgrading via the '/Library/Developer/CommandLineTools/usr/bin/python3 -m pip install --upgrade pip' command.
Note: you may need to restart the kernel to use updated packages.


In [ ]:
import numpy as np

In [ ]:
list = [1,2,3,4,5]
print(f" type of list is {type(list)}")
arr = np.array(list)
print(f" type of arr is {type(arr)}")
print(arr)

 type of list is <class 'list'>
 type of arr is <class 'numpy.ndarray'>
[1 2 3 4 5]


In [ ]:
list = [[1, 2], [3, 4]]
arr2 = np.array(list)
print(arr2)

[[1 2]
 [3 4]]


In [ ]:
# IMPORTANT PROPERTIES
# arr is numpy array that's why these methods works on normal array it shows error
print(arr.shape)      # dimensions
print(arr.ndim)       # number if axes
print(arr.size)       # total elements
print(arr.dtype)      # data type

(5,)
1
5
int64


In [ ]:
np.zeros((2,3))     # create 2X3 matrics with all zeros
np.ones((2,3))      # create 2X3 matrics with al ones
np.eye(3)           # create 3X3 identity matrix
np.arange(0,10,2)   # from 0 t0 10 with difference of 2
np.linspace(0,1,5)  # evenly spaced linspace(start, stop, num) create num values between start and stop with evenly spaced

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [ ]:
# SLICING
list = [10, 20, 30, 40]
arr = np.array(list)
print(arr[0])
print(arr[1:3])  # print elements from index "1 to (3-1)"

10
[20 30]


In [ ]:
arr2 = np.array([[1,2,3], [3,4,5]])
print(arr2[0,1])
print(arr2[:1])

2
[[1 2 3]]


In [ ]:
# MATHS OPERATIONS
a = np.array([1,2,3])
b = np.array([4,5,6])
# here index to index operation is performed so both array need to be
# of same dimensions

print(type(a), type(b))
print(a*b)
# print( a ** b)
print(a + b)
print(np.sqrt(a))
print(np.sum(a))
print(np.mean(b))

<class 'numpy.ndarray'> <class 'numpy.ndarray'>
[ 4 10 18]
[5 7 9]
[1.         1.41421356 1.73205081]
6
5.0


In [ ]:
# BROADCASTING
a = np.array([1,2,3])
b = 2
print(a * b)

[2 4 6]


In [ ]:
# RESHAPING ARRAYS
# convert lineat arry to defined matrix size but ahow error if not possibel
# to create the matrix

arr = np.arange(9)
print(arr)
print(arr.reshape(3,3))


[0 1 2 3 4 5 6 7 8]
[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [ ]:
# RANDOM NUMBERS
print(np.random.rand(3))           # between 0 to 1 random three numbers
np.random.randint(1,10,3)   # between 1 to 10 random three numbers

[0.02661346 0.34992348 0.45830639]


array([2, 8, 3])

In [ ]:
# FUNCTIONS
arr = [1,3,2,4,5,100]
print(np.max(arr))
np.min(arr)
print(np.argmax(arr))       # return the index of the max number
np.sort(arr)          # By default ascending order
np.sort(arr)[::-1]    # [::-1] means reverse the array, first sort the arry then reverse
                      # so descending order

np.flip(np.sort(arr)) # for descending order


100
5


array([100,   5,   4,   3,   2,   1])

In [ ]:
arr = np.arange(1,11)
arr.reshape(2,5)
np.mean(arr)
print(arr * 3)
print(arr[len(arr)-1])

[ 3  6  9 12 15 18 21 24 27 30]
10


# Advanced Indexing


In [ ]:
import numpy as np

In [ ]:
arr = np.array([10, 20, 30, 40, 50])
# condition
# use it to filter
print(arr>25)         # print true or false at each index
print(arr[arr>25])    # print value at index if true

[False False  True  True  True]
[30 40 50]


In [ ]:
# multiple conditions
# AND -> &
# OR -> |
# NOT -> ~

print((arr > 10) & (arr < 40))
print(arr[(arr > 10) & (arr < 40)])

[False  True  True False False]
[20 30]


In [ ]:
# FANCY INDEXING
arr = np.array([10,20,30,40,])
print(arr[[0,2]])       # can pick random position directly
                        # print the values at index 0 and 2
print(np.random.choice(arr,3)) # randomly pick 3 values from array dont use .randint

[10 30]
[40 20 30]


In [ ]:
# Boolean Masking
marks = np.array([45,67,30,90])
# student who passed (> 50)
print(marks[marks > 50])

[67 90]


In [ ]:
# PRACTICE
dict = {
    "tarun": 65,
    "arun": 67,
    "varun": 90
}
for key, val in dict.items():
  if(val > 65):
    print(key)

arun
varun


In [ ]:
# AXIS CONCEPT

# Array Type	Valid Axis
# 1D	only axis=0
# 2D	axis=0, axis=1
# 3D	axis=0,1,2

arr = np.array([[1,2,3],
                  [4,5,6]])

# arr = np.array([1,2,3,4])
# “axis = 0 means column-wise, so output should be (1,2,3,4)”
# 👉 This logic works for 2D arrays, but not for 1D arrays
# "It Combine all elements along the only available axis”


print(np.sum(arr, axis=0))        # sum the elements column wise
np.sum(arr, axis=1)               # sum the elements row wise

[5 7 9]


array([ 6, 15])

In [ ]:
arr = np.array([[1,2,3],
               [4,5,6]])
vec = np.array([10,20,30])      # should be equal to number of colns
print(arr + vec)


[[11 22 33]
 [14 25 36]]


In [ ]:
# WHERE FUNCTION
arr = np.array([10,20,30,40])
result = np.where(arr >= 30, "high", "low")     #if true print high else low
print(result)

['low' 'low' 'high' 'high']


In [ ]:
import numpy as np
arr = np.array([12,45,67,23,89,34])
print(arr)
print(arr > 30)
print(arr[arr > 30])
result = np.where(arr < 30, 0, arr)
print(result)
print(arr.argsort())      # arrange arr in ascending and print their index
                          # at first is the index of smallest ele
print(np.argmax(arr))     # index of max element
print(np.argmin(arr))     # index of min element
print(np.sort(arr))
print(np.sort(arr)[::-1])
print(np.flip(np.sort(arr))) # ANOTHER WAY TO PRINT IN DESCENDING ORDER


[12 45 67 23 89 34]
[False  True  True False  True  True]
[45 67 89 34]
['0' '45' '67' '0' '89' '34']
[0 3 5 1 2 4]
4
0
[12 23 34 45 67 89]
[89 67 45 34 23 12]
[89 67 45 34 23 12]


# Advance NumPy level


In [ ]:
# Vector and matrices basics
import numpy as np

# vector
a = np.array([1,2,3])

# matrix
A = np.array([[1,2],
             [4,5]])


In [ ]:
# Dot Product
# Used in:
# Machine Learning
# Neural Networks
# Similarity calculations

a = np.array([1,2,3])
b = np.array([4,5,6])

print(np.dot(a,b)) # 1*4 + 2*5 + 3*6 = 32

32


In [ ]:
# Matrix Multiplication
A = np.array([[1,2],
              [3,4]])
B = np.array([[5,6],
              [7,8]])

print(np.dot(A,B))
# OR
print(A @ B)


[[19 22]
 [43 50]]
[[19 22]
 [43 50]]


In [ ]:
# Transpose
A = np.array([[1,2,3],
              [4,5,6]])
print(A.T)

[[1 4]
 [2 5]
 [3 6]]


In [ ]:
# Determinant
A = np.array([[1,2],[3,4]])
result = np.linalg.det(A)       # linalg-> linear algebra module inside numpy
                                # to perform mathema. operat. related to matrices and vectors

# Round value -> change the value
print(round(result, 7))     # Python removes unnecessary trailing zeros that why output is -2.0

# format display -> changes how the number looks
print(f"{result:.7f}")      # print upto 7 places after point

-2.0
-2.0000000


In [ ]:
# Inverse the matrix
A = np.array([[1,2],
              [3,4]])
inv_A = np.linalg.inv(A)
print(inv_A)

print(np.round(np.dot(A ,inv_A),2))

[[-2.   1. ]
 [ 1.5 -0.5]]
[[1. 0.]
 [0. 1.]]


In [ ]:
# Eigen vectors and Values
# Used in:
# PCA (Dimensionality reduction)
# ML models
# Physics simulations

A = np.array([[2,0],
              [0,3]])
values, vectors = np.linalg.eig(A)
print(values)
print(vectors)

[2. 3.]
[[1. 0.]
 [0. 1.]]


In [ ]:
# Linear Equation
# 2x + y = 5
# x + y = 3

A = np.array([[2,1],
              [1,1]])
B = np.array([5,3])

result = np.linalg.solve(A,B)   # solve the linear equation
print(result)

[2. 1.]


In [ ]:
# Norm (Vector length or magnitude of vector)
# root(x^2 + y^2 + .....)

# Used in:
# Distance calculation
# ML optimization

# DISTANCE BETWEEN POINTS
a = np.array([3,4])
b = np.array([5,6])

A = a - b
print(A)

distance = np.linalg.norm(A)
print(round(distance, 2))
print(f"{distance:.4f}")


[-2 -2]
2.83
2.8284


In [ ]:
import numpy as np
A = np.array([[2,3],
             [1,4]])

B = np.array([[5,6],
              [7,8]])

print(A * B)  # Not A Matrix Multiplication
print(np.dot(A, B))
# OR
print(A@B)

print(f"{np.linalg.det(A):.2f}")

inv_a = np.linalg.inv(A)
print(inv_a)
print(np.round(np.dot(A, inv_a),2))
np.allclose(np.dot(A, inv_a), np.eye(2))

print(B.T)

x = np.array([[2,3],
              [1,2]])
y = np.array([8,5])

result = np.linalg.solve(x,y)
print(result)

[[10 18]
 [ 7 32]]
[[31 36]
 [33 38]]
[[31 36]
 [33 38]]
5.00
[[ 0.8 -0.6]
 [-0.2  0.4]]
[[ 1. -0.]
 [ 0.  1.]]
[[5 7]
 [6 8]]
[1. 2.]


# NumPy in real world

In [ ]:
import numpy as np
img = np.array([[0,255,100],
                [50, 200,150]])


In [ ]:
# brightness increase
img = img + 50
print(img)

[[ 50 305 150]
 [100 250 200]]


In [ ]:
# crop image
# Similar patterns
# Code	Meaning
# img[:, 1:]	remove first column
# img[:, :-1]	remove last column
# img[1:, :]	remove first row
# img[:-1, :]	remove last row

cropped = img[:, 1:] # take all rows but remove the first column
print(cropped)

[[305 150]
 [250 200]]


In [ ]:
# Flip image
print(img)
flipped = np.flip(img, axis = 1)      # columns (horizontal direction)
print(flipped)

[[ 50 305 150]
 [100 250 200]]
[[150 305  50]
 [200 250 100]]


In [ ]:
arr = np.arange(1000000)
print(arr*2)

[      0       2       4 ... 1999994 1999996 1999998]


In [ ]:
# It specifies the data type of the array elements
# 👉 int8 means: 8-bit signed integer
# What is “8-bit”?
# 👉 8 bits = 1 byte
# 👉 It can store 256 values
# Since it’s signed:
# Range: -128 to 127

# Memory Efficient
# int8  → 1 byte per element
# int32 → 4 bytes per element
# int64 → 8 bytes per element

arr = np.array([1,2,3], dtype = np.int8)
# arr = np.array([1,2,3], dtype = np.int64)
print(arr.nbytes)

3


In [ ]:
# View
arr = np.array([1,2,3,4])
view = arr[1:3]       # SLICING RETURN VIEW
                      # VIEW SHARES THE SAME MEMORY AS ORIGINAL ARRAY

print(view)
view[0] = 100
view[1] = 200
# arr[1] = 500
print(view)
print(arr)

[2 3]
[100 200]
[  1 100 200   4]


In [ ]:
# copy
copy = arr.copy()
print(copy)

[  1 100 200   4]


In [ ]:
# STACKING ARRAYS
a = np.array([1,2])
b = np.array([3,4])
print(np.vstack((a,b,a,a))) # veritcal (like rowwise)
print(np.hstack((b,a)))     # horizontal (like columnwise)

[[1 2]
 [3 4]
 [1 2]
 [1 2]]
[3 4 1 2]


In [ ]:
# SPLITING ARRAYS
arr = np.array([1,2,3,4,5,6])
np.split(arr,2)       # Split arr into two equal length parts


[array([1, 2, 3]), array([4, 5, 6])]

In [ ]:
# working with nan/ missing data
arr = np.array([1,2,3,np.nan,4])
np.isnan(arr)       # return boolean array, show nan is present or not
np.nanmean(arr)     # calculate mean not including nan


np.float64(2.5)

In [ ]:
# numpy + Pandas (real data science)
import pandas as pd

df = pd.DataFrame(np.random.rand(5,3))
print(df)

          0         1         2
0  0.736818  0.769412  0.953349
1  0.818945  0.285013  0.538671
2  0.580173  0.692883  0.035642
3  0.311546  0.199937  0.009337
4  0.469358  0.184196  0.231342


In [ ]:
# real ML ex
X = np.array([1,2,3,4])
w = 2
b = 1
prediction = X * w + b
print(prediction)

[3 5 7 9]


In [ ]:
import numpy as np
data = np.array([10,20,np.nan, 40, 50, np.nan, 70])

mean = np.nanmean(data)
print(mean)
result = np.where(np.isnan(data), mean, data)     # np.nan is not equal to anything, even itself
                                              # np.nan == np.nan is false
print(result)

normalized = (result - np.min(result)) / (np.max(result) - np.min(result))
print(normalized)

values = result[result >30]
print(values)

data.reshape(7,1)

38.0
[10. 20. 38. 40. 50. 38. 70.]
[0.         0.16666667 0.46666667 0.5        0.66666667 0.46666667
 1.        ]
[38. 40. 50. 38. 70.]


array([[10.],
       [20.],
       [nan],
       [40.],
       [50.],
       [nan],
       [70.]])

# Problems

In [ ]:
# Find duplicate elements
import numpy as np

arr = np.array([1,2,3,2,4,5,1])
unique , count = np.unique(arr, return_counts = True) # This does two things:
                                                      # Finds unique values
                                                      # Counts how many times each value appears
duplicates = unique[count > 1]
print(duplicates)

[1 2]


In [ ]:
# Normalize Data
arr = np.array([10,20,30,40,50])
norm = (arr - np.min(arr)) / (np.max(arr) - np.min(arr))
print(norm)

[0.   0.25 0.5  0.75 1.  ]


In [ ]:
# Replace value based on condition
arr = np.array([10,25,30,25,5])
result = np.where(arr > 10, 0, arr)
print(result)

[10  0  0  0  5]


In [ ]:
# Row-wise sum
arr = np.array([[1,2,3],
                [4,5,6]])
result = np.sum(arr ,axis = 0)
result1 = np.sum(arr, axis=1)
print(result)
print(result1)

[5 7 9]
[ 6 15]


In [ ]:
# Find Top K elements
arr = np.array([10,40,30,20,50])
k = 3
top_k = np.sort(arr)[-k:]
print(top_k)

[30 40 50]


In [ ]:
# Matrix multilication
a = np.array([[1,2],
              [3,4]])
b = np.array([[5,6],
              [7,8]])
print(np.dot(a,b))

[[19 22]
 [43 50]]


In [ ]:
# Flatten Array
arr = np.array([[1,2,3,45],
               [4,5,6,7]])
print(arr.flatten())

[ 1  2  3 45  4  5  6  7]


In [ ]:
# count even
arr = np.array([1,2,3,4,5,6])
count = 0
for val in arr:
  if val % 2 == 0 :
    count += 1

print(count)

# OR

new_count = np.sum(arr%2 == 0)
print(new_count)

3
3


In [ ]:
# Reverse arr
arr = np.array([1,2,3,4,5])
reverse = np.flip(arr)
# OR
print(arr[::-1])
print(reverse)

[5 4 3 2 1]
[5 4 3 2 1]


In [ ]:
# Missing value handling
arr = np.array([10,20,np.nan, 40])
print(np.isnan(arr))
mean = np.nanmean(arr)
arr = np.round(np.where(np.isnan(arr), mean, arr) ,2 )
print(arr)

[False False  True False]
[10.   20.   23.33 40.  ]
